package com.imnaiyar.skytimes.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val LightColor = lightColorScheme(
    background = Color(0xfffcf8fd),
    error = Color(0xffba1a1a),
    errorContainer = Color(0xffffdad6),
    inverseOnSurface = Color(0xfff4eff4),
    inversePrimary = Color(0xffc7bfff),
    inverseSurface = Color(0xff313034),
    onBackground = Color(0xff1c1b1f),
    onError = Color(0xffffffff),
    onErrorContainer = Color(0xff93000a),
    onPrimary = Color(0xffffffff),
    onPrimaryContainer = Color(0xff44369c),
    onSecondary = Color(0xffffffff),
    onSecondaryContainer = Color(0xff47445c),
    onSurface = Color(0xff1c1b1f),
    onSurfaceVariant = Color(0xff47464a),
    onTertiary = Color(0xffffffff),
    onTertiaryContainer = Color(0xff65394e),
    outline = Color(0xff78767b),
    outlineVariant = Color(0xffcac6d6),
    primary = Color(0xff5c4fb6),
    primaryContainer = Color(0xffe5deff),
    scrim = Color(0xff000000),
    secondary = Color(0xff5f5b75),
    secondaryContainer = Color(0xffe5dffd),
    surface = Color(0xfffcf8fd),
    surfaceTint = Color(0xff5c4fb6),
    surfaceVariant = Color(0xffe5e1e6),
    tertiary = Color(0xff7f5066),
    tertiaryContainer = Color(0xffffd8e7),
    surfaceBright = Color(0xfffcf8fd),
    surfaceDim = Color(0xffddd9dd),
    surfaceContainer = Color(0xfff1ecf1),
    surfaceContainerHigh = Color(0xffebe7ec),
    surfaceContainerHighest = Color(0xffe5e1e6),
    surfaceContainerLow = Color(0xfff7f2f7),
    surfaceContainerLowest = Color(0xffffffff),
)

val DarkColor = darkColorScheme(
    background = Color(0xff141316),
    error = Color(0xffffb4ab),
    errorContainer = Color(0xff93000a),
    inverseOnSurface = Color(0xff313034),
    inversePrimary = Color(0xff5c4fb6),
    inverseSurface = Color(0xffe5e1e6),
    onBackground = Color(0xffe5e1e6),
    onError = Color(0xff690005),
    onErrorContainer = Color(0xffffdad6),
    onPrimary = Color(0xff2d1a85),
    onPrimaryContainer = Color(0xffe5deff),
    onSecondary = Color(0xff302e44),
    onSecondaryContainer = Color(0xffe5dffd),
    onSurface = Color(0xffe5e1e6),
    onSurfaceVariant = Color(0xffc9c5ca),
    onTertiary = Color(0xff4b2338),
    onTertiaryContainer = Color(0xffffd8e7),
    outline = Color(0xff929094),
    outlineVariant = Color(0xff4d4a58),
    primary = Color(0xffc7bfff),
    primaryContainer = Color(0xff44369c),
    scrim = Color(0xff000000),
    secondary = Color(0xffc8c3e0),
    secondaryContainer = Color(0xff47445c),
    surface = Color(0xff141316),
    surfaceTint = Color(0xffc7bfff),
    surfaceVariant = Color(0xff47464a),
    tertiary = Color(0xfff1b6d0),
    tertiaryContainer = Color(0xff65394e),
    surfaceBright = Color(0xff3a383c),
    surfaceDim = Color(0xff141316),
    surfaceContainer = Color(0xff201f23),
    surfaceContainerHigh = Color(0xff2a292d),
    surfaceContainerHighest = Color(0xff353438),
    surfaceContainerLow = Color(0xff1c1b1f),
    surfaceContainerLowest = Color(0xff0e0e11),
)