name: Release app

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build APK
        run: |
          chmod +x gradlew
          echo "${{ secrets.KEYSTORE }}" | base64 -d > androidApp/keystore
          
          ./gradlew :androidApp:assembleRelease
        env:
          KEYSTORE_FILE_PATH: keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Create Github Release
        id: create-release
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
          files: |
            androidApp/build/outputs/apk/release/*.apk